# Generated by Django 3.1.3 on 2020-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201117_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
