# Generated by Django 3.1.3 on 2020-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='point',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
