# Generated by Django 3.1.3 on 2020-11-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201117_0725'),
        ('movie', '0004_auto_20201118_0728'),
        ('analysis', '0002_auto_20201117_0725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_log',
            new_name='UserLog',
        ),
    ]
