# Generated by Django 3.1.3 on 2020-11-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20201118_0728'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlog',
            table='user_logs',
        ),
    ]
