# Generated by Django 3.1.3 on 2020-11-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20201117_0613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_Actor',
            new_name='MovieActor',
        ),
        migrations.RenameModel(
            old_name='Movie_Genre',
            new_name='MovieGenre',
        ),
    ]
