# Generated by Django 3.1.3 on 2020-11-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20201118_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='movie',
            new_name='movies',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='movie',
            new_name='movies',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='contry',
            new_name='country',
        ),
        migrations.AlterModelTable(
            name='movieactor',
            table='movie_actors',
        ),
        migrations.AlterModelTable(
            name='moviegenre',
            table='movie_genres',
        ),
    ]
