# Generated by Django 3.1.3 on 2020-11-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20201118_0728'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movieactor',
            table='movie_actors',
        ),
    ]
