# Generated by Django 3.1.3 on 2020-11-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20201121_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='contry',
            new_name='country',
        ),
    ]
